service: ai-model

provider:
  name: aws
  runtime: nodejs10.x
  profile: shawn2911
  # environment:
  #   tableName: ${self:custom.settings.NODES_TABLE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        "*"
        # - "arn:aws:dynamodb:us-east-1:*:table/${self:custom.settings.NODES_TABLE}"

plugins:
  - serverless-s3-sync

custom:
  settings:
    NODES_TABLE: nodes
    ACTIVATION_FUNCTIONS_TABLE: activationFunctions
    LAYER_TABLE: layers
    LAYER_NODES_TABLE: layer_nodes
    LAYER_TRANSACTION: layer_transactions
    TRANSACTION_TABLE: transactions
  s3Sync:
    - bucketName: myveryfirstprojectuploadbucketwithserverless-29111997
      localDir: upload

functions:
  # ACTIVATION FUNCTIONS
  getAllActivationFunctions:
    handler: endpoints/activationFunction/getAllActivationFunctions.handler
    events:
      - http:
          path: api/activationFunctions
          method: GET
          cors: true
  getActivationFunction:
    handler: endpoints/activationFunction/getActivationFunction.handler
    events:
      - http:
          path: api/activationFunctions/{id}
          method: GET
          cors: true
  addActivationFunction:
    handler: endpoints/activationFunction/addActivationFunction.handler
    events:
      - http:
          path: api/activationFunctions
          method: POST
          cors: true
  updateActivationFunction:
    handler: endpoints/activationFunction/updateActivationFunction.handler
    events:
      - http:
          path: api/activationFunctions/{id}
          method: PUT
          cors: true
  deleteActivationFunction:
    handler: endpoints/activationFunction/deleteActivationFunction.handler
    events:
      - http:
          path: api/activationFunctions/{id}
          method: DELETE
          cors: true
          # authorizer: aws_iam
  # NODES
  getNode:
    handler: endpoints/node/getNode.handler
    events:
      - http:
          path: api/nodes/{id}
          method: GET
          cors: true
  getAllNodes:
    handler: endpoints/node/getAllNodes.handler
    events:
      - http:
          path: api/nodes
          method: GET
          cors: true
  addNode:
    handler: endpoints/node/addNode.handler
    events:
      - http:
          path: api/nodes
          method: POST
          cors: true
  updateNode:
    handler: endpoints/node/updateNode.handler
    events:
      - http:
          path: api/nodes/{id}
          method: PUT
          cors: true
  deleteNode:
    handler: endpoints/node/deleteNode.handler
    events:
      - http:
          path: api/nodes/{id}
          method: DELETE
          cors: true
  # LAYERS
  getLayer:
    handler: endpoints/layer/getLayer.handler
    events:
      - http:
          path: api/layers/{id}
          method: GET
          cors: true
  getAllLayers:
    handler: endpoints/layer/getAllLayers.handler
    events:
      - http:
          path: api/layers
          method: GET
          cors: true
  addLayer:
    handler: endpoints/layer/addLayer.handler
    events:
      - http:
          path: api/layers
          method: POST
          cors: true
  updateLayer:
    handler: endpoints/layer/updateLayer.handler
    events:
      - http:
          path: api/layers/{id}
          method: PUT
          cors: true
  deleteLayer:
    handler: endpoints/layer/deleteLayer.handler
    events:
      - http:
          path: api/layers/{id}
          method: DELETE
          cors: true
  # LAYER_NODES
  pushNode:
    handler: endpoints/layer/pushNode.handler
    events:
      - http:
          path: api/layers/nodes
          method: POST
          cors: true
  getNodes:
    handler: endpoints/layer/getNodes.handler
    events:
      - http:
          path: api/layers/nodes/{id}
          method: GET
          cors: true
  # LAYER_TRANSACTIONS (LAYER_ACTIVATION_FUNCTIONS)
  pushActivationFunction:
    handler: endpoints/layer/pushActivationFunction.handler
    events:
      - http:
          path: api/transactions
          method: POST
          cors: true
  getTransactions:
    handler: endpoints/layer/getTransactions.handler
    events:
      - http:
          path: api/transactions
          method: GET
          cors: true
  deleteTransaction:
    handler: endpoints/layer/deleteTransaction.handler
    events:
      - http:
          path: api/transactions/{id}
          method: DELETE
          cors: true
  updateTransaction:
    handler: endpoints/layer/updateTransaction.handler
    events:
      - http:
          path: api/transactions/{id}
          method: PUT
          cors: true
  # TRANSACTIONS
  getAllV2Transactions:
    handler: endpoints/transaction/getTransactions.handler
    events:
      - http:
          path: api/v2/transactions
          method: GET
          cors: true
  getV2TransactionsByPage:
    handler: endpoints/transaction/getTransactionsByPage.handler
    events:
      - http:
          path: api/v2/transactions/{page}
          method: GET
          cors: true
  getV2CurrentTransaction:
    handler: endpoints/transaction/getCurrentTransaction.handler
    events:
      - http:
          path: api/v2/transactions/current
          method: GET
          cors: true
  addV2Transactions:
    handler: endpoints/transaction/addTransaction.handler
    events:
      - http:
          path: api/v2/transactions
          method: POST
          cors: true

resources:
  Resources:
    DemoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: myveryfirstprojectuploadbucketwithserverless-291119972
    NodesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.NODES_TABLE}
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    ActivationFunctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.ACTIVATION_FUNCTIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    LayersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.LAYER_TABLE}
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    LayerNodesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.LAYER_NODES_TABLE}
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    LayerTransactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.LAYER_TRANSACTION}
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    TransactionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.settings.TRANSACTION_TABLE}
        AttributeDefinitions:
          - AttributeName: "_id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "_id"
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
